export const CATEGORIES: string[] = [
  "Apparel",
  "Automobiles & Motorcycle",
  "Beauty & Personal Care",
  "Computer Hardware & Software",
  "Consumer Electronics",
  "Consumer Electronics Accessories",
  "Electrical Equipment & Supplies",
  "Electronic Components & Supplies",
  "Fashion Accessories",
  "Food & Beverage",
  "Furniture",
  "Gifts & Crafts",
  "Hardware",
  "Health & Medical",
  "Home & Garden",
  "Home Appliances",
  "Lights & Lighting",
  "Luggage, Bags & Cases",
  "Machinery",
  "Office & School Supplies",
  "Packaging & Printing",
  "Pet Supplies",
  "Shoes & Accessories",
  "Sports & Entertainment ",
  "Telecommunications",
  "Textiles & Leather Products",
  "Timepieces, Jewelry, Eyewear",
  "Tools",
  "Toys & Hobbies",
  "Transportation"
]
